name: yeticave-aleksandr

services:
    php:
        build:
            context: php
            dockerfile: Dockerfile
            args:
                PHP_VERSION: '8.5'
                FPM_PORT: 9000
                DIR: /app
        container_name: yeticave-aleksandr-php
        env_file:
            - ./../../.env
        hostname: localhost
        restart: unless-stopped
        volumes:
            - ../../:/app
            - ./php/php.ini:/usr/local/etc/php/php.ini:ro
        working_dir: /

    nginx:
        image: nginx:1.21
        container_name: yeticave-aleksandr-nginx
        environment:
            LISTEN_HTTP: 80
            PHP_FPM_HOST: php
            PHP_FPM_PORT: 9000
        ports:
            - '8980:80'
        restart: unless-stopped
        volumes:
            - ../../:/app
            - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
        working_dir: /

    mysql:
        image: mysql
        container_name: yeticave-aleksandr-mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
        ports:
            - '8906:3306'
        restart: no
        volumes:
            - mysql_data:/var/lib/mysql
            - ./mysql/:/docker-entrypoint-initdb.d/:ro

volumes:
    mysql_data:
        driver: local
